package testing;

import java.util.Arrays;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Collectors;
import soot.G;
import soot.PackManager;
import soot.options.Options;
import soot.Transform;
import java.io.FileOutputStream;
import java.io.PrintStream;

public class Driver {

    // Each entry: { classPath, mainClass, reflLog, label }
    static final String[][] BENCHMARKS = {
            {
                "out",                           // [0] classPath = TamiFlex-dumped dir
                "Harness",                       // [1] mainClass = always "Harness" for DaCapo
                "tests/reflogs/sunflow.log",     // [2] reflection log
                "sunflow"                        // [3] label for output files
            },
    };

    /**
     * Writes a filtered copy of the TamiFlex log to a temp file, stripping
     * any line whose method signature belongs to a JVM-synthesised $$Lambda$
     * class (e.g. java.awt.GraphicsEnvironment$$Lambda$1.1972439101).
     *
     * WHY THIS IS SAFE:
     *   Every $$Lambda$ class in the sunflow log belongs to the "java.*" or
     *   "sun.*" excluded packages (java.awt, java.time, sun.java2d, …).
     *   Soot already excludes those packages from analysis, so these entries
     *   would contribute nothing to the call graph.  The real benchmark
     *   reflective calls (org.dacapo.harness.Sunflow, org.sunflow.Benchmark,
     *   etc.) contain no $$Lambda$ and are left completely untouched.
     *
     * WHY WE FILTER RATHER THAN PATCH SOOT:
     *   These classes are runtime-generated by LambdaMetafactory and have no
     *   stable .class file on the analysis classpath. Soot creates a skeleton
     *   SootClass for them but registers no method stubs, so
     *   Scene.v().getMethod(sig) throws RuntimeException regardless of
     *   phantom-ref or force-resolve workarounds applied in cg/wjtp packs.
     */
    static String filteredLog(String originalLog) throws Exception {
        Path src = Paths.get(originalLog);
        String filtered = Files.lines(src)
                               .filter(line -> !line.contains("$$Lambda$"))
                               .collect(Collectors.joining("\n"));

        Path tmp = Files.createTempFile("tamiflex_filtered_", ".log");
        Files.write(tmp, filtered.getBytes());
        tmp.toFile().deleteOnExit();
        return tmp.toString();
    }

    public static void main(String[] args) throws Exception {
    	long start = System.nanoTime();
        for (String[] bench : BENCHMARKS) {
            String classPath = bench[0];
            String mainClass = bench[1];
            String reflLog   = bench[2];
            String label     = bench[3];

            String outFile = "tests/results/" + label + "_result.txt";
            new java.io.File("tests/results").mkdirs();
            PrintStream out = new PrintStream(new FileOutputStream(outFile));
            System.setOut(out);
            System.setErr(out);

            System.out.println("=== Benchmark: " + label + " ===");

            // Filter $$Lambda$ entries from the log before handing it to Soot.
            // The original file is never modified.
            String filteredReflLog = filteredLog(reflLog);
            System.out.println("Using filtered reflection log: " + filteredReflLog);

            G.reset();

            Options.v().set_no_bodies_for_excluded(true);
            Options.v().set_allow_phantom_refs(true);
            Options.v().set_whole_program(true);

            Options.v().set_include(Arrays.asList(
                "org.apache.",
                "org.w3c",
                "java.lang.invoke."   // keeps LambdaForm$* resolvable from the log
            ));
            Options.v().set_exclude(Arrays.asList(
                "java.", "javax.", "sun.", "com.sun."
            ));

            String jreLib = System.getProperty("java.home") + "/lib";
            String[] sootArgs = {
                "-cp", classPath
                      + ";" + jreLib + "/rt.jar"
                      + ";" + jreLib + "/jce.jar"
                      + ";" + jreLib + "/jsse.jar"
                      + ";dacapo-9.12-MR1-bach.jar",
                "-pp",
                "-w", "-app",
                "-src-prec", "class",
                "-f", "class",
                "-d", "tests/checking1/" + label,
                "-p", "cg.spark", "enabled:true",
                "-p", "cg", "reflection-log:" + filteredReflLog,  // ← filtered copy
                mainClass
            };

            CalIGraphAnalysis analysis = new CalIGraphAnalysis();
            PackManager.v().getPack("wjtp")
                           .add(new Transform("wjtp.mhpA", analysis));

            try {
                soot.Main.main(sootArgs);
                System.out.println("=== DONE: " + label + " ===");
            } catch (Exception e) {
                System.out.println("=== FAILED: " + label + " ===");
                e.printStackTrace();
            }

            out.flush();
            out.close();
        }
        long end = System.nanoTime();
        // Restore stdout so IDE console shows completion
        System.setOut(new PrintStream(new FileOutputStream(java.io.FileDescriptor.out)));
        System.out.println("All benchmarks complete. Results in tests/results/");
        System.out.println("Time taken (ms): " + ((end - start) / 1_000_000));
    }
}